#if UNITY_EDITOR

using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;

namespace AIToUGUI.Editor
{
    internal static class AIToUGUIPanelCodeGenUtility
    {
        private static readonly Regex IdentifierPartRegex = new Regex("[A-Za-z0-9]+", RegexOptions.Compiled);

        public static string BuildDefaultPanelTypeName(string pageId, string prefabName)
        {
            var source = SelectPrimaryName(pageId, prefabName);
            var identifier = BuildPascalIdentifier(source);
            if (string.IsNullOrWhiteSpace(identifier))
            {
                identifier = "Page";
            }

            if (identifier.EndsWith("GeneratedPanel", StringComparison.Ordinal))
            {
                return identifier;
            }

            if (identifier.EndsWith("Panel", StringComparison.Ordinal))
            {
                identifier = identifier.Substring(0, identifier.Length - "Panel".Length);
            }

            return $"{identifier}GeneratedPanel";
        }

        public static bool EnsureGeneratedPanelScript(string siteId, string panelTypeName, out string scriptPath, out bool created)
        {
            created = false;
            scriptPath = BuildGeneratedPanelScriptPath(siteId, panelTypeName);
            if (string.IsNullOrWhiteSpace(scriptPath))
            {
                return false;
            }

            var folder = Path.GetDirectoryName(scriptPath)?.Replace("\\", "/");
            TryMigrateLegacyGeneratedPanelFolder(siteId, folder);
            EnsureFolder(folder);

            if (!File.Exists(scriptPath))
            {
                File.WriteAllText(scriptPath, RenderBasePanelScript(panelTypeName), Encoding.UTF8);
                AssetDatabase.ImportAsset(scriptPath, ImportAssetOptions.ForceUpdate);
                created = true;
            }

            return true;
        }

        public static bool TryGetGeneratedPanelScriptPath(string siteId, string panelTypeName, out string scriptPath)
        {
            scriptPath = BuildGeneratedPanelScriptPath(siteId, panelTypeName);
            return !string.IsNullOrWhiteSpace(scriptPath) && File.Exists(scriptPath);
        }

        private static string BuildGeneratedPanelScriptPath(string siteId, string panelTypeName)
        {
            if (string.IsNullOrWhiteSpace(panelTypeName))
            {
                return null;
            }

            return AIToUGUIGeneratedAssetPaths.GetGeneratedPanelScriptPath(siteId, panelTypeName);
        }

        private static string RenderBasePanelScript(string panelTypeName)
        {
            var builder = new StringBuilder(256);
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine();
            builder.Append("public partial class ").Append(panelTypeName).AppendLine(" : AIToUGUIViewPanel");
            builder.AppendLine("{");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string SelectPrimaryName(string pageId, string prefabName)
        {
            if (!string.IsNullOrWhiteSpace(prefabName) &&
                !string.Equals(prefabName, "CompiledPage", StringComparison.Ordinal) &&
                !string.Equals(prefabName, "PagePanel", StringComparison.Ordinal))
            {
                return prefabName;
            }

            return pageId;
        }

        private static string BuildPascalIdentifier(string rawValue)
        {
            if (string.IsNullOrWhiteSpace(rawValue))
            {
                return string.Empty;
            }

            var matches = IdentifierPartRegex.Matches(rawValue);
            if (matches.Count == 0)
            {
                return string.Empty;
            }

            var builder = new StringBuilder(rawValue.Length);
            for (var i = 0; i < matches.Count; i++)
            {
                var part = matches[i].Value;
                if (string.IsNullOrWhiteSpace(part))
                {
                    continue;
                }

                builder.Append(char.ToUpperInvariant(part[0]));
                if (part.Length > 1)
                {
                    builder.Append(part.Substring(1));
                }
            }

            if (builder.Length == 0)
            {
                return string.Empty;
            }

            if (char.IsDigit(builder[0]))
            {
                builder.Insert(0, "AIToUGUI");
            }

            return builder.ToString();
        }

        private static string SanitizePathSegment(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "Default";
            }

            var sanitized = value.Trim();
            foreach (var invalid in Path.GetInvalidFileNameChars())
            {
                sanitized = sanitized.Replace(invalid, '_');
            }

            return string.IsNullOrWhiteSpace(sanitized) ? "Default" : sanitized;
        }

        private static void TryMigrateLegacyGeneratedPanelFolder(string siteId, string targetFolder)
        {
            if (string.IsNullOrWhiteSpace(siteId) ||
                string.IsNullOrWhiteSpace(targetFolder) ||
                AssetDatabase.IsValidFolder(targetFolder))
            {
                return;
            }

            var legacyFolder = AIToUGUIGeneratedAssetPaths.GetLegacyGeneratedPanelFolder(siteId);
            if (!AssetDatabase.IsValidFolder(legacyFolder))
            {
                return;
            }

            var packageRoot = AIToUGUIGeneratedAssetPaths.GetPackageRoot(siteId);
            EnsureFolder(packageRoot);
            AssetDatabase.MoveAsset(legacyFolder, targetFolder);
        }

        private static void EnsureFolder(string folderPath)
        {
            if (string.IsNullOrWhiteSpace(folderPath) || AssetDatabase.IsValidFolder(folderPath))
            {
                return;
            }

            var normalized = folderPath.Replace("\\", "/").TrimEnd('/');
            var parent = Path.GetDirectoryName(normalized)?.Replace("\\", "/");
            if (!string.IsNullOrWhiteSpace(parent) && !AssetDatabase.IsValidFolder(parent))
            {
                EnsureFolder(parent);
            }

            var folderName = Path.GetFileName(normalized);
            if (!string.IsNullOrWhiteSpace(parent) && !string.IsNullOrWhiteSpace(folderName))
            {
                AssetDatabase.CreateFolder(parent, folderName);
            }
        }
    }
}

#endif
